# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2017, 1, 14, 20, 24, 39, 302445))),
                ('Topic', models.TextField(max_length=200)),
                ('Blog_Image', models.ImageField(upload_to=b'')),
                ('Content_para_1', models.TextField(max_length=700)),
                ('Content_para_2', models.TextField(max_length=700)),
                ('Content_para_3', models.TextField(max_length=700)),
                ('Content_para_4', models.TextField(max_length=700)),
                ('Content_para_5', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2017, 1, 14, 20, 24, 39, 305312))),
                ('News_Topic', models.TextField(max_length=200)),
                ('News_Content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=15)),
                ('PhoneNo', models.TextField(max_length=10)),
                ('Emailid', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.TextField(max_length=20)),
                ('Product_Model', models.TextField(max_length=20)),
                ('Product_Image', models.ImageField(upload_to=b'')),
                ('Product_Description_Para1', models.TextField(max_length=500)),
                ('Product_Description_Para2', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Gen_Name', models.TextField(max_length=20)),
                ('Product_Disp_Image', models.ImageField(default='', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research_Topic', models.TextField(max_length=200)),
                ('Research_Description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Research_TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2017, 1, 14, 20, 24, 39, 304471))),
                ('Activity', models.TextField(blank=True, default=datetime.datetime(2017, 1, 14, 20, 24, 39, 304519))),
                ('Research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Research')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Product_Category'),
        ),
    ]
