# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2016, 12, 9, 22, 11, 49, 233242))),
                ('Topic', models.TextField(max_length=200)),
                ('Blog_Image', models.ImageField(upload_to='')),
                ('Content_para_1', models.TextField(max_length=700)),
                ('Content_para_2', models.TextField(max_length=700)),
                ('Content_para_3', models.TextField(max_length=700)),
                ('Content_para_4', models.TextField(max_length=700)),
                ('Content_para_5', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2016, 12, 9, 22, 11, 49, 235409))),
                ('News_Topic', models.TextField(max_length=200)),
                ('News_Content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.TextField(max_length=20)),
                ('Product_Model', models.TextField(max_length=20)),
                ('Product_Image', models.ImageField(upload_to='')),
                ('Product_Description_Para1', models.TextField(max_length=500)),
                ('Product_Description_Para2', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Gen_Name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research_Topic', models.TextField(max_length=200)),
                ('Research_Description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Research_TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2016, 12, 9, 22, 11, 49, 234759))),
                ('Activity', models.TextField(blank=True, default=datetime.datetime(2016, 12, 9, 22, 11, 49, 234801))),
                ('Research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Research')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Product_Category'),
        ),
    ]
