# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-10 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20161210_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 10, 21, 32, 37, 376526)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 10, 21, 32, 37, 378848)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Activity',
            field=models.TextField(blank=True, default=datetime.datetime(2016, 12, 10, 21, 32, 37, 378243)),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 10, 21, 32, 37, 378204)),
        ),
    ]
