# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20170115_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('sales_staff', 'sales staff'), ('sales_man', 'sales manager'), ('admin', 'administrator'), ('design', 'desin_staff'), ('tech', 'tech_manager'), ('accountman', 'accounts_manager'), ('accounts', 'accounts_staff'), ('purchase', 'purchase_staff'), ('purchaseman', 'purchase_manager'))},
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 15, 13, 4, 10, 907757)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 15, 13, 4, 10, 909519)),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Activity',
            field=models.TextField(blank=True, default=datetime.datetime(2017, 1, 15, 13, 4, 10, 909002)),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 15, 13, 4, 10, 908967)),
        ),
    ]
