# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20161210_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='Product_Disp_Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 11, 7, 53, 13, 282663)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 11, 7, 53, 13, 284334)),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Activity',
            field=models.TextField(blank=True, default=datetime.datetime(2016, 12, 11, 7, 53, 13, 283868)),
        ),
        migrations.AlterField(
            model_name='research_timeline',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 11, 7, 53, 13, 283840)),
        ),
    ]
